### ISSUE TITLE
does not work in processing 2.11

### ISSUE THREAD

**Issue by sterlingcrispin** [joonhyublee/joons-renderer#7]
Hey there

I've used this renderer in 2.0.3 with good results, however it doesn't work in 2.1.1 and throws a null pointer exception.

the basic example runs, but the fill example and others throw a null pointer exception. I don't have time to fully investigate what exactly is happening there. The wireframes will draw but if you ask it to render it crashes.

**Comment by sntx** [comment]
Hey there, got a fix for the jr.background(r,g,b) issue, created pull request. https://github.com/sntx/joons-renderer/commit/99c7cb2fef7be6b75b6d77c6a2bb751b7493e48a

**Comment by joonhyublee** [comment]
Merged!

**Comment by cacheflowe** [comment]
Radical, thanks @sntx !
