### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by sntx** [joonhyublee/joons-renderer#8]
Hey, would love to fix some issues in the library and expand it. Could you please provide build instructions? Thanks

**Comment by joonhyublee** [comment]
Hey i welcome it. I dont know what you mean by build instruction tho. I always used eclipse to run the code files and used the export feature on it to create a jar, which i think was a simple zip of the things? I have all the dependencies uploaded on my git as well, in any case. Try for urself, and let me know if you run into any problem. Thanks!

**Comment by sntx** [comment]
I see, so do you run processing from Eclipse? test the library by just running from Eclipse and then export only the library? I'll work on setting this up, thanks for the help.

**Comment by joonhyublee** [comment]
Yea thats the idea. Um make sure to use the version of Processing that was around when the lib was last updated? Let me know how things go. Thanks!

**Comment by sntx** [comment]
Got it working with the latest version of Processing, created pull request.

**Comment by joonhyublee** [comment]
Thats cool! Keep up the good work :)
